### ISSUE TITLE
The Feature "removePresetByIds" is not working

### ISSUE THREAD

**Issue by kPlock** [vaadin-component-factory/vcf-date-range-picker-flow#45]
We use the DateRangePicker with Sidebar enabled. We want to hide the "original" Buttons and we add our own, but the removing is not working anymore:

Sample code:

<img width="628" alt="Bildschirmfoto 2024-02-14 um 14 21 48" src="https://github.com/vaadin-component-factory/vcf-date-range-picker-flow/assets/13207847/3db01dae-349e-45cb-b124-2e714836a1dc">

Result:
<img width="446" alt="Bildschirmfoto 2024-02-14 um 14 21 30" src="https://github.com/vaadin-component-factory/vcf-date-range-picker-flow/assets/13207847/21983520-b365-404d-ab06-47aa936bda1d">

**Comment by HerbertsVaadin** [comment]
Seems like there's an issue with the js component. [THIS](https://github.com/vaadin-component-factory/vcf-date-range-picker/blob/71ce9d1f49ed9cd16e30c6f66f2ca82b8d2d29f2/src/vcf-date-range-picker-mixin.js#L1152) line should be executed when dialog / overlay is opened or closed it seems, but it only gets executed when closing.

**Comment by HerbertsVaadin** [comment]
Workaround CSS to remove / hide all presets
```css
vcf-date-range-picker-overlay-content::part(today-button),
vcf-date-range-picker-overlay-content::part(preset-button),
vcf-date-range-picker-overlay-content::part(cancel-button) {
    display: none;
}
```

But for our case, we want to remove only the 'yesterday' preset, which requires to put the CSS in `frontend/themes/mytheme/components/vcf-date-range-picker-overlay-content.css` 
```css
:host vaadin-button#yesterdayButton {
    display: none;
}
```
